import keepAccount.composite.*;

import java.util.ArrayList;
import java.util.List;

public class Main {
    public static void main(String[] args) {
        
        BookStack library = new BookStack();
        List<BookStack> bookShelfs = new ArrayList<BookStack>();
        
        int y = 2021;
        int m = 1;
        
        for (m = 1; m <= 11; m++) {
            BookStack newBookShelf = new BookStack(y, m);
            bookShelfs.add(newBookShelf);
            library.add(newBookShelf);
        }
        
        m = 0;
        BookStack january = bookShelfs.get(++m - 1);
        BookStack february = bookShelfs.get(++m - 1);
        february.add(new Book("これだけで身につくPerl入門例題80", y, m, 4, "メルペイ残高", "メルカリ", 300, 224));
        february.add(new Book("初めてのPerl", y, m, 4, "メルペイ残高", "メルカリ", 510));
        february.add(new Book("JavaScript本格入門", y, m, 6, "メルペイ残高", "メルカリ", 700));
        february.add(new Book("実践力を身につけるPythonの教科書", y, m, 8, "メルペイ残高", "メルカリ", 990, 11));
        february.add(new Book("作りながら学ぶHTML/CSSデザインの教科書", y, m, 8, "メルペイ残高", "メルカリ", 800));
        february.add(new Book("いきなりはじめるPHP", y, m, 12, "メルペイ残高", "メルカリ", 650, 12));
        february.add(new Book("たのしいC#プログラミング", y, m, 12, "クレジットカード", "ラクマ", 1200));
        february.add(new Book("10日でおぼえるPerl/CGI入門教室", y, m, 13, "メルペイ残高", "メルカリ", 300, 10));
        february.add(new Book("ゲームで学ぶJavaScript入門", y, m, 13, "クレジットカード", "メルカリ", 999, 417));
        february.add(new Book("ゲームで学ぶJavaScript入門", y, m, 13, "メルペイ残高", "メルカリ", 417));
        february.add(new Book("10日でおぼえるHTML5入門教室", y, m, 14, "クレジットカード", "メルカリ", 400, 0));
        february.add(new Book("XHTML+CSS Webコンテンツデザインガイド", y, m, 16, "クレジットカード", "メルカリ", 300, 23));
        february.add(new Book("HTML5Canvas", y, m, 22, "クレジットカード", "メルカリ", 450, 270, 14));
        february.add(new Book("HTML5Canvas", y, m, 22, "メルペイ残高", "メルカリ", 270));
        february.add(new Book("WordPress仕事の現場でサッと使える！デザイン教科書", y, m, 22, "クレジットカード", "メルカリ", 850));
        february.add(new Book("C++クラスと継承完全制覇", y, m, 23, "クレジットカード", "メルカリ", 720, 14));
        february.add(new Book("詳解ActionScript3.0アニメーション", y, m, 23, "クレジットカード", "メルカリ", 390));
        february.add(new Book("CSS3デザインブック", y, m, 24, "クレジットカード", "メルカリ", 400));
        february.add(new Book("Head First PHP & MySQL", y, m, 25, "クレジットカード", "メルカリ", 840, 18));
        february.add(new Book("プログラミングRuby", y, m, 25, "クレジットカード", "メルカリ", 680));
        february.add(new Book("Head First Rails", y, m, 26, "メルペイ残高", "メルカリ", 450));
        BookStack march = bookShelfs.get(++m - 1);
        march.add(new Book("Sass & Compass徹底入門", y, m, 2, "クレジットカード", "メルカリ", 350, 28));
        march.add(new Book("Kivyプログラミング", y, m, 6, "クレジットカード", "メルカリ", 1500, 5));
        march.add(new Book("JavaScriptフレームワーク入門", y, m, 7, "クレジットカード", "メルカリ", 810));
        march.add(new Book("C言語によるはじめてのアルゴリズム入門", y, m, 7, "クレジットカード", "メルカリ", 900));
        march.add(new Book("CSSグリッドレイアウトデザインブック", y, m, 7, "クレジットカード", "メルカリ", 1500, 6));
        march.add(new Book("The R Tips", y, m, 24, "クレジットカード", "メルカリ", 1444, 69));
        march.add(new Book("現場で役立つjQueryデザインパーツライブラリ", y, m, 26, "クレジットカード", "メルカリ", 439));
        BookStack april = bookShelfs.get(++m - 1);
        april.add(new Book("WebデザイナーのためのjQuery入門", y, m, 5, "クレジットカード", "メルカリ", 498, 72, 27));
        BookStack may = bookShelfs.get(++m - 1);
        may.add(new Book("HTML5による物理シミュレーション", y, m, 8, "クレジットカード", "メルカリ", 1600));
        may.add(new Book("HTML5による物理シミュレーション 拡散・波動編", y, m, 8, "クレジットカード", "メルカリ", 1300));
        may.add(new Book("Head First C", y, m, 28, "クレジットカード", "メルカリ", 980, 30));
        may.add(new Book("SQL書き方ドリル", y, m, 31, "クレジットカード", "メルカリ", 780));
        BookStack june = bookShelfs.get(++m - 1);
        june.add(new Book("パーフェクトPHP", y, m, 1, "クレジットカード", "メルカリ", 650, 29, 4));
        june.add(new Book("PHPによるWebアプリケーションスーパーサンプル 活用編", y, m, 4, "クレジットカード", "メルカリ", 780, 6));
        june.add(new Book("PHPで始めるWebアプリケーション開発", y, m, 4, "メルペイスマート払い", "メルカリ", 300));
        june.add(new Book("いまどきのアルゴリズムを使いこなすPHPプログラミング", y, m, 4, "メルペイスマート払い", "メルカリ", 300));
        june.add(new Book("WordPress関数リファレンスガイド", y, m, 12, "メルペイスマート払い", "メルカリ", 400, 39, 5));
        june.add(new Book("PHPによるWordPressカスタマイズブック", y, m, 12, "メルペイスマート払い", "メルカリ", 400));
        june.add(new Book("jQueryクックブック", y, m, 12, "メルペイスマート払い", "メルカリ", 500));
        june.add(new Book("10日でおぼえるPHP入門教室", y, m, 14, "メルペイスマート払い", "メルカリ", 400, 2));
        june.add(new Book("10日でおぼえるPerl/CGI入門教室", y, m, 16, "メルペイ残高", "メルカリ", 410, 2));
        june.add(new Book("プロを目指す人のためのRuby入門", y, m, 18, "クレジットカード", "ラクマ", 1400));
        june.add(new Book("創るJava", y, m, 20, "メルペイ残高", "メルカリ", 1000, 2));
        june.add(new Book("新・明解Pythonで学ぶアルゴリズムとデータ構造", y, m, 26, "メルペイ残高", "メルカリ", 2100, 9));
        june.add(new Book("Web designer's handbook", y, m, 30, "メルペイ残高", "メルカリ", 300, 105, 10));
        june.add(new Book("Ajax Webアプリケーションアイデアブック", y, m, 30, "メルペイ残高", "メルカリ", 300));
        june.add(new Book("HTML5インタラクティブ表現ガイド", y, m, 30, "メルペイ残高", "メルカリ", 400));
        june.add(new Book("JavaScriptビジュアル・リファレンス", y, m, 30, "クレジットカード", "メルカリ", 600, 208));
        june.add(new Book("JavaScriptビジュアル・リファレンス", y, m, 30, "メルペイ残高", "メルカリ", 208));
        BookStack july = bookShelfs.get(++m - 1);
        july.add(new Book("Amazon Web Services 基礎からのネットワーク＆サーバー構築", y, m, 2, "クレジットカード", "メルカリ", 890));
        july.add(new Book("独習LaTeX2e", y, m, 5, "クレジットカード", "メルカリ", 1100, 17));
        july.add(new Book("Head First JavaScript", y, m, 6, "クレジットカード", "メルカリ", 840));
        july.add(new Book("Head First ネットワーク", y, m, 6, "メルペイスマート払い", "メルカリ", 1200));
        july.add(new Book("基礎Perl", y, m, 9, "Amazonギフトカード", "Amazon", 558));
        july.add(new Book("Head First C#", y, m, 10, "メルペイ残高", "メルカリ", 810, 50));
        july.add(new Book("シェルスクリプト基本リファレンス", y, m, 12, "メルペイ残高", "メルカリ", 840));
        july.add(new Book("Head First Java", y, m, 13, "クレジットカード", "ラクマ", 1011, 50));
        july.add(new Book("Javaによるアルゴリズム事典", y, m, 14, "メルペイ残高", "メルカリ", 500, 12));
        july.add(new Book("超図解C#ルールブック", y, m, 14, "Amazonギフトカード", "Amazon", 321));
        july.add(new Book("開眼！JavaScript", y, m, 15, "メルペイ残高", "メルカリ", 600));
        july.add(new Book("独習XML", y, m, 15, "Amazonギフトカード", "Amazon", 345));
        july.add(new Book("すべての人のためのJavaプログラミング", y, m, 16, "Amazonギフトカード", "Amazon", 2530));
        july.add(new Book("実戦で役立つC#プログラミングのイディオム/定石＆パターン", y, m, 16, "Amazonギフトカード", "Amazon", 2722));
        july.add(new Book("Head First データ解析", y, m, 16, "Amazonギフトカード", "Amazon", 497));
        july.add(new Book("Go言語ハンズオン", y, m, 18, "メルペイ残高", "メルカリ", 2200, 27, 134));
        july.add(new Book("Go言語ハンズオン", y, m, 18, "メルペイスマート払い", "メルカリ", 134));
        july.add(new Book("JS+Node.jsによるWebクローラー／ネットエージェント開発テクニック", y, m, 22, "Amazonギフトカード", "Amazon", 380));
        july.add(new Book("Pythonクローリング＆スクレイピング", y, m, 24, "メルペイ残高", "メルカリ", 980, 45));
        july.add(new Book("HTML5スマホアプリ開発の教科書", y, m, 27, "メルペイ残高", "メルカリ", 500));
        july.add(new Book("HTML5ハイブリッドアプリ開発実践入門", y, m, 27, "メルペイ残高", "メルカリ", 450));
        july.add(new Book("LaTeX2eコマンドブック", y, m, 29, "Amazonギフトカード", "Amazon", 320));
        BookStack august = bookShelfs.get(++m - 1);
        august.add(new Book("UNIXコマンドブック", y, m, 3, "メルペイ残高", "メルカリ", 720, 27));
        august.add(new Book("Python実践入門", y, m, 3, "メルペイ残高", "メルカリ", 2100));
        august.add(new Book("パーフェクトJavaScript", y, m, 5, "クレジットカード", "ラクマ", 650));
        august.add(new Book("JavaScript the good parts", y, m, 8, "メルペイ残高", "メルカリ", 400, 41));
        august.add(new Book("詳解WordPress", y, m, 8, "クレジットカード", "メルカリ", 720, 683));
        august.add(new Book("詳解WordPress", y, m, 8, "メルペイ残高", "メルカリ", 683));
        august.add(new Book("SQLパズル", y, m, 12, "クレジットカード", "メルカリ", 1000, 6));
        august.add(new Book("ウェブ配色ミニ帳", y, m, 14, "クレジットカード", "メルカリ", 300, 10));
        august.add(new Book("プログラミングのための線形代数", y, m, 15, "メルペイスマート払い", "メルカリ", 1990));
        august.add(new Book("PHP5 & XMLによるWebサービス構築", y, m, 15, "Amazonギフトカード", "Amazon", 321));
        august.add(new Book("実例で学ぶゲーム3D数学", y, m, 20, "メルペイスマート払い", "メルカリ", 1400, 48));
        august.add(new Book("Head First デザインパターン", y, m, 24, "メルペイ残高", "メルカリ", 1800, 21));
        august.add(new Book("CSS逆引きデザインレシピ", y, m, 25, "クレジットカード", "ラクマ", 500));
        august.add(new Book("エンジニアのためのWordPress開発入門", y, m, 26, "クレジットカード", "ラクマ", 1500, 200));
        BookStack september = bookShelfs.get(++m - 1);
        september.add(new Book("Ajax Hacks", y, m, 5, "Amazonギフトカード", "Amazon", 281));
        september.add(new Book("実践Ruby on Rails 4", y, m, 9, "クレジットカード", "Amazon", 269));
        september.add(new Book("Ajaxデザインパターン", y, m, 11, "メルペイ残高", "メルカリ", 450, 27));
        september.add(new Book("Javaデザインパターン徹底攻略", y, m, 12, "クレジットカード", "メルカリ", 333, 117));
        september.add(new Book("Javaデザインパターン徹底攻略", y, m, 12, "メルペイ残高", "メルカリ", 117));
        september.add(new Book("Javaアルゴリズム＋データ構造完全制覇", y, m, 12, "クレジットカード", "Amazon", 269));
        september.add(new Book("Javaデザインパターン：プログラミングの実際pt.2", y, m, 13, "クレジットカード", "メルカリ", 980));
        september.add(new Book("Javaデザインパターン：プログラミングの実際pt.1", y, m, 13, "クレジットカード", "Amazon", 549));
        september.add(new Book("Pythonではじめる数学の冒険", y, m, 22, "メルペイ残高", "メルカリ", 2900, 24));
        september.add(new Book("Larabelリファレンス", y, m, 27, "クレジットカード", "Amazon", 366));
        september.add(new Book("いまどきのJSプログラマーのためのNode.jsとReactアプリケーション開発テクニック", y, m, 30, "クレジットカード", "メルカリ", 1950, 965));
        september.add(new Book("いまどきのJSプログラマーのためのNode.jsとReactアプリケーション開発テクニック", y, m, 30, "メルペイ残高", "メルカリ", 965));
        september.add(new Book("Vue.js入門", y, m, 30, "クレジットカード", "メルカリ", 2200));
        BookStack october = bookShelfs.get(++m - 1);
        october.add(new Book("Webデザインの現場で使えるVue.jsの教科書", y, m, 3, "クレジットカード", "Amazon", 2042));
        october.add(new Book("Land of Lisp", y, m, 12, "クレジットカード", "メルカリ", 1780, 75, 1404));
        october.add(new Book("Land of Lisp", y, m, 12, "メルペイ残高", "メルカリ", 1404));
        october.add(new Book("ゲームアルゴリズムコレクション for iOS", y, m, 13, "メルペイスマート払い", "メルカリ", 400));
        october.add(new Book("ブレイクスルーJavaScript", y, m, 16, "メルペイスマート払い", "メルカリ", 420, 26));
        october.add(new Book("NATURE OF CODE", y, m, 19, "メルペイスマート払い", "メルカリ", 3333, 6, 2961));
        october.add(new Book("NATURE OF CODE", y, m, 19, "メルペイ残高", "メルカリ", 2961));
        october.add(new Book("キタミ式イラストIT塾 応用情報技術者 令和03年", y, m, 22, "クレジットカード", "メルカリ", 1700, 6, 540));
        october.add(new Book("キタミ式イラストIT塾 応用情報技術者 令和03年", y, m, 22, "メルペイ残高", "メルカリ", 540));
        october.add(new Book("栢木先生の基本情報技術者教室", y, m, 27, "クレジットカード", "メルカリ", 400, 74));
        BookStack november = bookShelfs.get(++m - 1);
        november.add(new Book("ハッカーのたのしみ", y, m, 3, "メルペイスマート払い", "メルカリ", 500));
        november.add(new Book("独習Java", y, m, 4, "クレジットカード", "Amazon", 434));
        november.add(new Book("世界一わかりやすいSQLの授業", y, m, 5, "クレジットカード", "Amazon", 321));
        november.add(new Book("スラスラわかるJava", y, m, 20, "メルペイ残高", "メルカリ", 600, 52));
        november.add(new Book("Rubyの冒険 遊遊編", y, m, 20, "メルペイ残高", "メルカリ", 400));
        november.add(new Book("Rubyの冒険 旅立ち編", y, m, 20, "メルペイ残高", "メルカリ", 400));
        november.add(new Book("Javaネットワークプログラミング", y, m, 20, "クレジットカード", "Amazon", 320));
        november.add(new Book("SVGコーディングの基本", y, m, 24, "クレジットカード", "メルカリ", 1280, 21, 36));
        november.add(new Book("SVGコーディングの基本", y, m, 24, "メルペイ残高", "メルカリ", 36));
        
        library.dumpFile("compositeOutput");
    }
}
